- name: Adding IIS Roles and Features
  win_feature:
    name:
    - Web-Common-Http
    - Web-Security
    - Web-Mgmt-Service
    - Web-Mgmt-Console
    include_sub_features: yes
    include_management_tools: yes
    state: present
  register: iis_feature

- name: reboot if feature requires 
  win_reboot:
    reboot_timeout: 3600  
  when: iis_feature.reboot_required

- name: Create the Deploy virtual directory
  win_iis_virtualdirectory:
    name: deploy
    site: Default Web Site
    state: present
    physical_path: Z:\Deploy\

- name: Import WebAdministration module
  win_psmodule:
    name: WebAdministration
    state: present

- name: Add MIME Type for WIM files
  win_command: powershell.exe -
  args:
    stdin: "Add-WebConfigurationProperty //staticContent -name collection -value @{fileExtension='.wim'; mimeType='application/octet-stream'}"
  ignore_errors: yes  

- name: Add MIME Type for ISO files
  win_command: powershell.exe -
  args:
    stdin: "Add-WebConfigurationProperty //staticContent -name collection -value @{fileExtension='.iso'; mimeType='application/octet-stream'}"  
  ignore_errors: yes

- name: Install browsers
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
  - firefox
  - googlechrome